-- Prerelease memory pipeline cutover.
--
-- Memory generated by an older architecture and its durable work are not
-- compatible inputs for the current two-phase pipeline. Ordinary Vault files,
-- revisions, audit, Provider configuration, backups, and non-memory jobs are
-- deliberately preserved. Managed memory Markdown is removed through Vault
-- Core by the post-migration memory.reset_pipeline job.

DELETE FROM jobs WHERE job_type LIKE 'memory.%';

DELETE FROM memory_consolidation_state;
DELETE FROM memory_consolidation_proposals;
DELETE FROM memory_stage1_outputs;
DELETE FROM memory_candidates;
DELETE FROM memory_diagnostics;
DELETE FROM memory_fts;
DELETE FROM embedding_records WHERE object_type = 'memory';
DELETE FROM memories;

DROP TABLE memory_consolidation_state;

CREATE TABLE memory_consolidation_state (
    vault_id TEXT PRIMARY KEY,
    generation INTEGER NOT NULL DEFAULT 0 CHECK (generation >= 0),
    memory_summary TEXT NOT NULL DEFAULT '',
    last_input_hash TEXT,
    last_proposal_id TEXT,
    last_success_at INTEGER,
    pipeline_generation INTEGER NOT NULL DEFAULT 0 CHECK (pipeline_generation >= 0),
    regeneration_pending INTEGER NOT NULL DEFAULT 0 CHECK (regeneration_pending IN (0, 1)),
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (vault_id) REFERENCES vaults(id) ON DELETE CASCADE,
    FOREIGN KEY (vault_id, last_proposal_id)
        REFERENCES memory_consolidation_proposals(vault_id, id)
);

CREATE UNIQUE INDEX jobs_one_active_memory_reset_per_vault_idx
    ON jobs(vault_id)
    WHERE job_type = 'memory.reset_pipeline'
      AND status IN ('queued', 'running', 'retry_wait');
